### PR TITLE
feat: adding_inspect_command

### PR DESCRIPTION
**Pull request by mtsitrin**
It produces the following output:

```
>rollappd dymint inspect-state                                                                                                                         
 
badger 2023/11/14 22:57:22 INFO: All 9 tables opened in 1ms
badger 2023/11/14 22:57:22 INFO: Discard stats nextEmptySlot: 0
badger 2023/11/14 22:57:22 INFO: Set nextTxnTs to 960
badger 2023/11/14 22:57:22 INFO: Deleting empty file: /Users/mtsitrin/.rollapp/data/dymint/000019.vlog
LOADING STATE
{Version:{Consensus:{Block:11 App:0} Software:0.34.29} ChainID:demo-dymension-rollapp InitialHeight:1 LastBlockHeight:228 LastBlockID:A2FB95330C5CED13BF19ACF185A2D34B3A5D9C1DDAFE24755F9B982B414964AD:0:000000000000 LastBlockTime:2023-11-14 20:20:58.9466 +0000 UTC SLStateIndex:0 NextValidators:ValidatorSet{
  Proposer: Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
  Validators:
    Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
} Validators:ValidatorSet{
  Proposer: Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
  Validators:
    Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
} LastValidators:ValidatorSet{
  Proposer: Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
  Validators:
    Validator{974D38DE200B9FE7799A8174D4A63EBCE5A9644E PubKeyEd25519{9A25253229A1E8555142EADEB49A553564FBB8E243EE3B4CC2EDA6D713960C45} VP:1 A:0}
} LastHeightValidatorsChanged:1 ConsensusParams:{Block:{MaxBytes:22020096 MaxGas:-1 TimeIotaMs:1000} Evidence:{MaxAgeNumBlocks:100000 MaxAgeDuration:48h0m0s MaxBytes:1048576} Validator:{PubKeyTypes:[ed25519]} Version:{AppVersion:0}} LastHeightConsensusParamsChanged:1 LastResultsHash:[227 176 196 66 152 252 28 20 154 251 244 200 153 111 185 36 39 174 65 228 100 155 147 76 164 149 153 27 120 82 184 85] LastStoreHeight:228 BaseHeight:0 AppHash:[93 67 31 91 181 251 78 129 72 149 82 207 73 48 146 170 219 153 173 84 51 196 158 153 14 166 254 51 127 233 250 225]}
========================================
========================================
LOADING BLOCK AT HEIGHT:  228
&{Header:{Version:{Block:11 App:0} NamespaceID:[0 0 0 0 0 0 255 255] Height:228 Time:1699993258946600000 LastHeaderHash:[213 119 133 117 186 227 115 19 187 147 7 6 79 204 63 78 194 165 130 19 23 139 50 70 136 120 174 105 134 43 224 227] LastCommitHash:[200 246 102 142 219 94 32 122 61 244 107 5 104 100 131 84 104 115 3 232 130 50 86 247 162 112 165 0 210 64 218 232] DataHash:[227 176 196 66 152 252 28 20 154 251 244 200 153 111 185 36 39 174 65 228 100 155 147 76 164 149 153 27 120 82 184 85] ConsensusHash:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] AppHash:[189 69 19 200 50 9 218 65 249 105 68 156 193 136 33 175 163 93 65 204 43 190 72 42 55 208 78 192 107 226 92 90] LastResultsHash:[227 176 196 66 152 252 28 20 154 251 244 200 153 111 185 36 39 174 65 228 100 155 147 76 164 149 153 27 120 82 184 85] ProposerAddress:[151 77 56 222 32 11 159 231 121 154 129 116 212 166 62 188 229 169 100 78] AggregatorsHash:[0 101 30 131 140 174 39 153 235 217 182 199 212 159 59 63 26 75 70 0 102 231 202 120 246 111 161 245 39 15 153 50] ChainID:demo-dymension-rollapp} Data:{Txs:[] IntermediateStateRoots:{RawRootsList:[]} Evidence:{Evidence:[]}} LastCommit:{Height:227 HeaderHash:[213 119 133 117 186 227 115 19 187 147 7 6 79 204 63 78 194 165 130 19 23 139 50 70 136 120 174 105 134 43 224 227] Signatures:[[185 111 66 132 129 127 149 202 195 147 152 56 89 101 120 43 195 128 212 36 102 214 123 45 26 155 245 179 212 186 58 246 167 113 147 241 46 41 43 188 222 1 127 111 167 105 26 54 30 90 117 132 159 228 5 27 5 168 193 64 96 17 237 10]] TMSignature:CommitSig{F92A19893F30 by 974D38DE200B on 2 @ 2023-11-14T20:20:55.746649Z}}}
========================================
========================================
LOADING BLOCK RESPONSES AT HEIGHT:  228
end_block:<consensus_param_updates:<block:<max_bytes:22020096 max_gas:-1 > evidence:<max_age_num_blocks:100000 max_age_duration:<seconds:172800 > max_bytes:1048576 > validator:<pub_key_types:"ed25519" > > > begin_block:<events:<type:"coin_spent" attributes:<key:"spender" value:"rol17xpfvakm2amg962yls6f84z3kell8c5lkdf39v" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"coin_received" attributes:<key:"receiver" value:"rol1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8ptwd8w" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"transfer" attributes:<key:"recipient" value:"rol1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8ptwd8w" index:true > attributes:<key:"sender" value:"rol17xpfvakm2amg962yls6f84z3kell8c5lkdf39v" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"message" attributes:<key:"sender" value:"rol17xpfvakm2amg962yls6f84z3kell8c5lkdf39v" index:true > > events:<type:"coin_spent" attributes:<key:"spender" value:"rol1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8ptwd8w" index:true > attributes:<key:"amount" value:"2853881urax" index:true > > events:<type:"coin_received" attributes:<key:"receiver" value:"rol1ymq030nn3vpah8fv265l370s6qae85f883rhtq" index:true > attributes:<key:"amount" value:"2853881urax" index:true > > events:<type:"transfer" attributes:<key:"recipient" value:"rol1ymq030nn3vpah8fv265l370s6qae85f883rhtq" index:true > attributes:<key:"sender" value:"rol1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8ptwd8w" index:true > attributes:<key:"amount" value:"2853881urax" index:true > > events:<type:"message" attributes:<key:"sender" value:"rol1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8ptwd8w" index:true > > events:<type:"commission" attributes:<key:"amount" value:"27682648.319000000000000000urax" index:true > attributes:<key:"validator" value:"rolvaloper1ymq030nn3vpah8fv265l370s6qae85f8mh6ekc" index:true > > events:<type:"rewards" attributes:<key:"amount" value:"276826483.190000000000000000urax" index:true > attributes:<key:"validator" value:"rolvaloper1ymq030nn3vpah8fv265l370s6qae85f8mh6ekc" index:true > > events:<type:"epoch_end" attributes:<key:"epoch_number" value:"3" index:true > > events:<type:"epoch_start" attributes:<key:"epoch_number" value:"3" index:true > attributes:<key:"start_time" value:"1697916255" index:true > > events:<type:"epoch_end" attributes:<key:"epoch_number" value:"3" index:true > > events:<type:"epoch_start" attributes:<key:"epoch_number" value:"3" index:true > attributes:<key:"start_time" value:"1697750655" index:true > > events:<type:"epoch_end" attributes:<key:"epoch_number" value:"3" index:true > > events:<type:"coin_received" attributes:<key:"receiver" value:"rol1m3h30wlvsf8llruxtpukdvsy0km2kum8w9dff3" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"coinbase" attributes:<key:"minter" value:"rol1m3h30wlvsf8llruxtpukdvsy0km2kum8w9dff3" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"coin_spent" attributes:<key:"spender" value:"rol1m3h30wlvsf8llruxtpukdvsy0km2kum8w9dff3" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"coin_received" attributes:<key:"receiver" value:"rol17xpfvakm2amg962yls6f84z3kell8c5lkdf39v" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"transfer" attributes:<key:"recipient" value:"rol17xpfvakm2amg962yls6f84z3kell8c5lkdf39v" index:true > attributes:<key:"sender" value:"rol1m3h30wlvsf8llruxtpukdvsy0km2kum8w9dff3" index:true > attributes:<key:"amount" value:"285388127urax" index:true > > events:<type:"message" attributes:<key:"sender" value:"rol1m3h30wlvsf8llruxtpukdvsy0km2kum8w9dff3" index:true > > events:<type:"mint" attributes:<key:"epoch_number" value:"3" index:true > attributes:<key:"epoch_provisions" value:"285388127.853881278538812785" index:true > attributes:<key:"amount" value:"285388127" index:true > > events:<type:"epoch_start" attributes:<key:"epoch_number" value:"3" index:true > attributes:<key:"start_time" value:"1697750655" index:true > > events:<type:"epoch_end" attributes:<key:"epoch_number" value:"3" index:true > > events:<type:"epoch_start" attributes:<key:"epoch_number" value:"3" index:true > attributes:<key:"start_time" value:"1698953055" index:true > > >
```

### CODE REVIEW

**Review by ItayLevyOfficial — APPROVED** [review]
LGTM

**Comment by omritoptix** [comment]
what's the different between this command and export command? which also exports the state but to a genesis.json?

**Comment by mtsitrin** [comment]
> what's the difference between this command and export command which also exports the state but to a genesis.json?

the `export` command exports the app state, `dymint inspect-state` outputs dymint's db

**Comment by mtsitrin** [comment]
it's more similar to this
https://github.com/cometbft/cometbft/blob/main/cmd/cometbft/commands/inspect.go
(comet's feature is live server for debugging, but the concept the same)

**Review by omritoptix — APPROVED** [review]

**Pull request merged**
